# Generated by Django 2.1.7 on 2019-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
